name: n8n-automation

services:
  n8n:
    source:
      type: git
    build:
      type: docker
      dockerfile: Dockerfile
    ports:
      - port: 5678
        type: http
    env:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_URL
        value: ${ZEABUR_WEB_URL}
      - key: N8N_EDITOR_BASE_URL
        value: ${ZEABUR_WEB_URL}
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: your_secure_password_here
      - key: EXECUTIONS_PROCESS
        value: main
      - key: N8N_METRICS
        value: true
      - key: GENERIC_TIMEZONE
        value: UTC
    volumes:
      - name: n8n-data
        mount: /home/node/.n8n

  postgres:
    source:
      type: image
      image: postgres:15-alpine
    env:
      - key: POSTGRES_DB
        value: n8n
      - key: POSTGRES_USER
        value: n8n
      - key: POSTGRES_PASSWORD
        value: n8n_secure_password
    volumes:
      - name: postgres-data
        mount: /var/lib/postgresql/data

volumes:
  - name: n8n-data
  - name: postgres-data
